# Generated by Django 6.0.2 on 2026-02-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAY', 'Payment'), ('FRND', 'Friendship')], max_length=4)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_initiated', to='Users.user')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_received', to='Users.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
